#include <opencv2/opencv.hpp>
#include <opencv2/nonfree.hpp>
#include <vector>
using namespace cv;
using namespace std;
using namespace flann;
using namespace cvflann;

extern "C" {

typedef vector<Vec4i> vector_Vec4i;
typedef vector<Vec2s> vector_Vec2s;

Vec2s* std_vector_get_element( vector_Vec2s * v
                            , unsigned int vectorIdx
                            , unsigned int elementIdx );
Vec2s* item( int const i, vector_Vec2s const& v );
Vec2b* cv_create_Vec2b();
Vec2b* cv_create_Vec2b_2(uchar val0, uchar val1);
Vec3b* cv_create_Vec3b();
Vec3b* cv_create_Vec3b_3(uchar val0, uchar val1, uchar val2);
Vec4b* cv_create_Vec4b();
Vec4b* cv_create_Vec4b_4(uchar val0, uchar val1, uchar val2, uchar val3);
Vec2d* cv_create_Vec2d(); 
Vec2d* cv_create_Vec2d_2(double val0, double val1);
Vec3d* cv_create_Vec3d();
Vec3d* cv_create_Vec3d_3(double val0, double val1, double val2);
Vec4d* cv_create_Vec4d();
Vec4d* cv_create_Vec4d_4(double val0, double val1, double val2, double val3);
Vec6d* cv_create_Vec6d(); 
Vec6d* cv_create_Vec6d_6(double val0, double val1, double val2, double val3, double val4, double val5);
Vec2f* cv_create_Vec2f();
Vec2f* cv_create_Vec2f_2(float val0, float val1);
Vec3f* cv_create_Vec3f();
Vec3f* cv_create_Vec3f_3(float val0, float val1, float val2) ;
Vec4f* cv_create_Vec4f();
Vec4f* cv_create_Vec4f_4(float val0, float val1, float val2, float val3) ;
Vec6f* cv_create_Vec6f(); 
Vec6f* cv_create_Vec6f_6(float val0, float val1, float val2, float val3, float val4, float val5);
Vec2i* cv_create_Vec2i();
Vec2i* cv_create_Vec2i_2(int val0, int val1);
Vec3i* cv_create_Vec3i();
Vec3i* cv_create_Vec3i_3(int val0, int val1, int val2);
Vec4i* cv_create_Vec4i(); 
Vec4i* cv_create_Vec4i_4(int val0, int val1, int val2, int val3);
Vec6i* cv_create_Vec6i();
Vec6i* cv_create_Vec6i_6(int val0, int val1, int val2, int val3, int val4, int val5);
Vec8i* cv_create_Vec8i();
Vec8i* cv_create_Vec8i_8(int val0, int val1, int val2, int val3, int val4, int val5, int val6, int val7);
Vec2s* cv_create_Vec2s();
Vec2s* cv_create_Vec2s_2(short val0, short val1);
Vec3s* cv_create_Vec3s();
Vec3s* cv_create_Vec3s_3(short val0, short val1, short val2) ;
Vec4s* cv_create_Vec4s();
Vec4s* cv_create_Vec4s_4(short val0, short val1, short val2, short val3);
Vec2w* cv_create_Vec2w();
Vec2w* cv_create_Vec2w_2(ushort val0, ushort val1);
Vec3w* cv_create_Vec3w();
Vec3w* cv_create_Vec3w_3(ushort val0, ushort val1, ushort val2);
Vec4w* cv_create_Vec4w();
Vec4w* cv_create_Vec4w_4(ushort val0, ushort val1, ushort val2, ushort val3);
void cv_LineSegmentDetector_detect2(LineSegmentDetector* self, Mat* _image, vector_Vec4i* _lines, Mat* width, Mat* prec, Mat* nfa);
void cv_LineSegmentDetector_drawSegments2(LineSegmentDetector* self, Mat* _image, vector_Vec4i* lines);
CvDTreeParams* cv_create_CvDTreeParams();
CvDTreeParams* cv_create_CvDTreeParams9(int max_depth, int min_sample_count, float regression_accuracy, bool use_surrogates, int max_categories, int cv_folds, bool use_1se_rule, bool truncate_pruned_tree, const float* priors);
Mat* cv_Mat_with_Range(Mat* self, Range* rowRange, Range* colRange);
Range* cv_create_Range(int _start, int _end);
Range* cv_create_RangeAll();
bool cv_Range_empty(Range* self);
int cv_Range_size(Range* self);
int cv_Range_getstart(Range* self);
int cv_Range_getend(Range* self);
void cv_HOGDescriptor_detectMultiScale9_2(HOGDescriptor* self, Mat* img, vector_Rect* foundLocations, double hitThreshold, Size* winStride, Size* padding, double scale, double finalThreshold, bool useMeanshiftGrouping);
void cv_HOGDescriptor_setSVMDetector2(HOGDescriptor* self, vector_float* _svmdetector);
CvSVMParams* cv_create_CvSVMParams(); 
//CvSVMParams* cv_create_CvSVMParams10(int svm_type, int kernel_type, double degree, double gamma, double coef0, double Cvalue, double nu, double p, CvMat class_weights, TermCriteria term_crit);
void cv_displayOverlay(String* winname, String* text, int delayms);
MatExpr* cv_abs(Mat* m);
Rect* cv_RotatedRect_boundingRect(RotatedRect* self);
MatExpr* cv_Mat_div(Mat* m1, Mat* m2);
FeatureDetector* cv_FeatureDetector_create2(FeatureDetector* self, const char* detectorType);
Scalar* cv_create_morphologyDefaultBorderValue();
bool cv_findChessboardCorners2(Mat* image, Size* patternSize, vector_Point2f* corners, int flags);
void cv_cornerSubPix2(Mat* image, vector_Point2f* corners, Size* winSize, Size* zeroZone, TermCriteria* criteria);
void cv_drawChessboardCorners2(Mat* image, Size* patternSize, vector_Point2f* corners, bool patternWasFound);
TermCriteria* cv_create_TermCriteria();
TermCriteria* cv_create_TermCriteria3(int type, int maxCount, double epsilon);
MatExpr* cv_Mat_sub(Mat* m1, Mat* m2);
RNG* cv_create_RNG();
RNG* cv_create_RNG_state(uint64 state);
double cv_RNG_uniform_double(RNG* self, double a, double b);
float cv_RNG_uniform_float(RNG* self, float a, float b);
int cv_RNG_uniform_int(RNG* self, int a, int b);
uchar* cv_Mat_get_Data(Mat* self);
Mat* cv_Mat_get_ROI(Mat* self, Rect* roi);
Mat* cv_imread2(const char* filename, int flags);
bool cv_imwrite2(const char* filename, Mat* img, vector_int* params);
FeatureDetector* cv_FeatureDetector_create2(FeatureDetector* self, const char* detectorType);
Size2f* cv_create_Size2f();
Size2f* cv_create_Size2f2(float width, float height);
Size2f* cv_Size_assignTo(Size2f* self, Size2f* other);
Size2f* cv_Size2f_fromPoint2f(Point2f* p);
float cv_Size2f_area(Size2f* self);
float cv_Size2f_width(Size2f* self);
float cv_Size2f_height(Size2f* self);
void cv_delete_CvANN_MLP(CvANN_MLP* self);
void cv_delete_CvANN_MLP_TrainParams(CvANN_MLP_TrainParams* self);
void cv_delete_CascadeClassifier(CascadeClassifier* self);
void cv_delete_DMatch(DMatch* ptr);
void cv_delete_CvDTree(CvDTree* self);
void cv_delete_CvDTreeParams(CvDTreeParams* self);
void cv_delete_Feature2D(Feature2D* self);
void cv_delete_HOGDescriptor(HOGDescriptor* self);
void cv_delete_KeyPoint(KeyPoint* self);
void cv_delete_CvKNearest(CvKNearest* self);
void cv_delete_CvNormalBayesClassifier(CvNormalBayesClassifier* self);
void cv_delete_Point(Point* self);
void cv_delete_Point2d(Point2d* self);
void cv_delete_Point2f(Point2f* self);
void cv_delete_Point3d(Point3d* self);
void cv_delete_Point3f(Point3f* self);
void cv_delete_Point3i(Point3i* self);
void cv_delete_Range(Range* self);
void cv_delete_Rect(Rect* self);
void cv_delete_RNG(RNG* self);
void cv_delete_RotatedRect(RotatedRect* self);
void cv_delete_Scalar(Scalar* self);
void cv_delete_Size(Size* self);
void cv_delete_Size2f(Size2f* self);
void cv_delete_TermCriteria(TermCriteria* self);
void cv_delete_Vec2b(Vec2b* self); 
void cv_delete_Vec3b(Vec3b* self);
void cv_delete_Vec4b(Vec4b* self); 
void cv_delete_Vec2d(Vec2d* self);
void cv_delete_Vec3d(Vec3d* self);
void cv_delete_Vec4d(Vec4d* self);
void cv_delete_Vec6d(Vec6d* self);
void cv_delete_Vec2f(Vec2f* self);
void cv_delete_Vec3f(Vec3f* self);
void cv_delete_Vec4f(Vec4f* self); 
void cv_delete_Vec6f(Vec6f* self);
void cv_delete_Vec2i(Vec2i* self);
void cv_delete_Vec3i(Vec3i* self);
void cv_delete_Vec4i(Vec4i* self);
void cv_delete_Vec6i(Vec6i* self);
void cv_delete_Vec8i(Vec8i* self); 
void cv_delete_Vec2s(Vec2s* self);
void cv_delete_Vec3s(Vec3s* self);
void cv_delete_Vec4s(Vec4s* self);
void cv_delete_Vec2w(Vec2w* self); 
void cv_delete_Vec3w(Vec3w* self);
void cv_delete_Vec4w(Vec4w* self);
void cv_delete_VideoCapture(VideoCapture* self);
void cv_delete_VideoWriter(VideoWriter* self);

}



